update freepbx15 to use php74.

diff --git a/overlay/usr/local/bin/freepbx15set b/overlay/usr/local/bin/freepbx15set
--- a/overlay/usr/local/bin/freepbx15set
+++ b/overlay/usr/local/bin/freepbx15set
@@ -2,47 +2,47 @@
 
 set_sslkey()
 {
-  shift
-  key=$@
-  if [ $? -eq 0 ] && [ "$key" != "" ] ; then
-    echo "Changing /usr/local/etc/apache24/ssl/private.key..."
-    echo "$key" > /usr/local/etc/apache24/ssl/private.key
-  else
-    echo "Error when updateing /usr/local/etc/apache24/ssl/private.key">2 ; exit 1
-  fi
-  exit 0
+	shift
+	key=$@
+	if [ $? -eq 0 ] && [ "$key" != "" ] ; then
+		echo "Changing /usr/local/etc/apache24/ssl/private.key..."
+		echo "$key" > /usr/local/etc/apache24/ssl/private.key
+	else
+		echo "Error when updateing /usr/local/etc/apache24/ssl/private.key">2 ; exit 1
+	fi
+	exit 0
 }
 
 set_sslcert()
 {
-  shift
-  cert=$@
-  if [ $? -eq 0 ] && [ "$cert" != "" ] ; then
-    echo "Changing /usr/local/etc/apache24/ssl/certificate.crt..."
-    echo "$cert" > /usr/local/etc/apache24/ssl/certificate.crt
-  else
-    echo "Error when updateing /usr/local/etc/apache24/ssl/certificate.crt">2 ; exit 1
-  fi
-  exit 0
+	shift
+	cert=$@
+	if [ $? -eq 0 ] && [ "$cert" != "" ] ; then
+		echo "Changing /usr/local/etc/apache24/ssl/certificate.crt..."
+		echo "$cert" > /usr/local/etc/apache24/ssl/certificate.crt
+	else
+		echo "Error when updateing /usr/local/etc/apache24/ssl/certificate.crt">2 ; exit 1
+	fi
+	exit 0
 }
 
 set_apacheconf()
 {
-  apacheconf=$@
-  if [ $? -eq 0 ] && [ $apacheconf != "" ] ; then
-    echo "Changing /usr/local/etc/apache24/Includes/freepbx15.conf..."
-    echo "$apacheconf" > /usr/local/etc/apache24/Includes/freepbx15.conf
-  else
-    echo "Error when updateing /usr/local/etc/apache24/Includes/freepbx15.conf">2 ; exit 1
-  fi
-  exit 0
+	apacheconf=$@
+	if [ $? -eq 0 ] && [ $apacheconf != "" ] ; then
+		echo "Changing /usr/local/etc/apache24/Includes/freepbx15.conf..."
+		echo "$apacheconf" > /usr/local/etc/apache24/Includes/freepbx15.conf
+	else
+		echo "Error when updateing /usr/local/etc/apache24/Includes/freepbx15.conf">2 ; exit 1
+	fi
+	exit 0
 }
 
 # Stub for something which sets quasselsettings
 case $1 in
-  sslkey) set_sslkey "$@" ;;
-  sslcert) set_sslcert "$@" ;;
-  apacheconf) set_apacheconf "$@" ;;
-  adminpasswd) set_adminpasswd $2 ;;
-  *) echo "Unknown option" ;;
+	sslkey) set_sslkey "$@" ;;
+	sslcert) set_sslcert "$@" ;;
+	apacheconf) set_apacheconf "$@" ;;
+	adminpasswd) set_adminpasswd $2 ;;
+	*) echo "Unknown option" ;;
 esac
